routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'ArticleController@newsfeed')->name('home');
Route::get('/spa', 'ArticleController@spa');

//While this returns JSON it isn't a proper Rest api
//because it isn't stateless and relies on the user's Session
//to customise the results according to the logged-in user.
Route::get('/newsfeed', 'ArticleController@newsfeedJson');

Route::post('articles/storeComment', 'ArticleController@storeComment');

Route::resource('articles', 'ArticleController');

Route::resource('pets', 'PetController', [
   'except' => ['show']
 ]);

 Route::get('/users/preferences', 'UserController@edit');
 Route::put('/users/updatepreferences', 'UserController@update');

Route::resource('users', 'UserController', [
  'only' => ['edit', 'update']
]);

Route::get('code', function(){
  return Redirect::to('https://bitbucket.org/danielelkington/pethelp/src/master/');
});

//Uncomment this to test how emails display!
// Route::get('/mailtest', function() {
//   $article = App\Article::find(4);
//   $user = App\User::find(1);
//   return new App\Mail\NewArticle($article, $user);
// });

app/Article.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;

class Article extends Model
{
    public function petTypes() {
      return $this->belongsToMany('App\PetType');
    }

    public function comments() {
      return $this->hasMany('App\Comment');
    }

    public function user() {
      return $this->belongsTo('App\User');
    }

    protected $appends = array('content_preview', 'content_preview_with_tags', 'days_old_description');

    public function getContentPreviewAttribute() {
      $preview = strip_tags($this->content);
      if (strlen($preview) < 50) {
        return $preview;
      }
      return substr($preview, 0, 50) . '...';
    }

    public function getContentPreviewWithTagsAttribute() {
      $preview = $this->html_cut($this->content, 200);
      return $preview;
    }

    public function getDaysOldDescriptionAttribute() {
      $daysOld = $this->created_at->diffInDays(Carbon::now());
      if ($daysOld === 0) {
        return "Today";
      }
      if ($daysOld === 1) {
        return "Yesterday";
      }
      return $daysOld . " days old";
    }

    //Neat little function from https://stackoverflow.com/a/2398820/5740181
    //Cuts a HTML string to specified length without breaking HTLM tags
    function html_cut($text, $max_length)
    {
        $tags   = array();
        $result = "";

        $is_open   = false;
        $grab_open = false;
        $is_close  = false;
        $in_double_quotes = false;
        $in_single_quotes = false;
        $tag = "";

        $i = 0;
        $stripped = 0;

        $stripped_text = strip_tags($text);

        while ($i < strlen($text) && $stripped < strlen($stripped_text) && $stripped < $max_length)
        {
            $symbol  = $text{$i};
            $result .= $symbol;

            switch ($symbol)
            {
               case '<':
                    $is_open   = true;
                    $grab_open = true;
                    break;

               case '"':
                   if ($in_double_quotes)
                       $in_double_quotes = false;
                   else
                       $in_double_quotes = true;

                break;

                case "'":
                  if ($in_single_quotes)
                      $in_single_quotes = false;
                  else
                      $in_single_quotes = true;

                break;

                case '/':
                    if ($is_open && !$in_double_quotes && !$in_single_quotes)
                    {
                        $is_close  = true;
                        $is_open   = false;
                        $grab_open = false;
                    }

                    break;

                case ' ':
                    if ($is_open)
                        $grab_open = false;
                    else
                        $stripped++;

                    break;

                case '>':
                    if ($is_open)
                    {
                        $is_open   = false;
                        $grab_open = false;
                        array_push($tags, $tag);
                        $tag = "";
                    }
                    else if ($is_close)
                    {
                        $is_close = false;
                        array_pop($tags);
                        $tag = "";
                    }

                    break;

                default:
                    if ($grab_open || $is_close)
                        $tag .= $symbol;

                    if (!$is_open && !$is_close)
                        $stripped++;
            }

            $i++;
        }

        while ($tags)
            $result .= "</".array_pop($tags).">";

        return $result;
    }
}

app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\View;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Log;
use App\PetType;
use App\Article;
use App\Comment;
use App\Http\Requests\StoreArticle;
use App\Http\Requests\StoreComment;
use App\Jobs\ProcessNewArticleEmails;
use Carbon\Carbon;
use Input;
use Redirect;
use Session;

class ArticleController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth', ['except' => [
            'spa',
            'newsfeed',
            'newsfeedJson',
            'show',
            'articleJson']]);
    }

    //Return the newsfeed of articles!
    public function newsfeed(Request $request)
    {
      $articles = $this->getNewsfeedArticles($request);
      return View::make('articles.newsfeed')->with('articles', $articles);
    }

    public function newsfeedJson(Request $request)
    {
      $articles = $this->getNewsfeedArticles($request);
      //Limit unnecesary properties from being returned in the JSON.
      $articles->makeHidden(['content', 'content_preview', 'user_id']);
      foreach($articles as $article) {
        $article->user->makeHidden(['id', 'is_subscribed', 'email', 'created_at', 'updated_at']);
      }
      return response()->json($articles, 200);
    }

    public function articleJson($id)
    {
      $article = Article::with('user')->with('comments.user')->find($id);
      $article->makeHidden(['content_preview', 'user_id', 'content_preview_with_tags']);
      $article->user->makeHidden(['id', 'is_subscribed', 'email', 'created_at', 'updated_at']);
      foreach($article->comments as $comment) {
        $comment->user->makeHidden(['id', 'is_subscribed', 'email', 'created_at', 'updated_at']);
      }
      return response()->json($article, 200);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $articles = Article::where('user_id', Auth::id())->get();
        return View::make('articles.index')->with('articles', $articles);
    }

    //Allows us to view a single page application version of the app.
    public function spa()
    {
      return View::make('layouts.spa');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
      $petTypes = $this->getPetTypeHierarchy();
      return View::make('articles.create')->with('petTypes', $petTypes);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreArticle $request)
    {
      $validated = $request->validated();

      Db::transaction(function() use ($request) {
        //1. Add the article
        $article = new Article;
        $article->title = $request->input('title');
        //Clean input to prevent XSS attacks!
        $article->content = clean($request->input('content'));
        $article->user_id = Auth::id();
        $article->save();
        //2. Add the pet Types
        $pettypeids = $request->input('pettype'); //[1, 2, 4]
        if ($pettypeids == NULL)
          $pettypeids = [];
        $article->petTypes()->sync($pettypeids);

        ProcessNewArticleEmails::dispatch($article)->onQueue('lowPriorityEmails');
      });

      //Redirect
      Session::flash('message', 'Successfully created article!');
      return Redirect::to('articles');
    }

    public function storeComment(StoreComment $request)
    {
        $validated = $request->validated();
        $comment = new Comment;
        $comment->content = $request->input('content');
        $comment->article_id = $request->input('article_id');
        $comment->user_id = Auth::id();
        $comment->save();

        //Redirect
        Session::flash('message', 'Successfully created comment!');
        return Redirect::to('articles/' . $comment->article_id);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
      $article = Article::with('comments')->with('user')->find($id);
      return View::make('articles.show')->with('article', $article);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $article = Article::find($id);
        $petTypes = $this->getPetTypeHierarchy();
        $checkedPetTypeIds = $article->petTypes()
                        ->pluck('pet_types.id')->toArray();

        foreach ($checkedPetTypeIds as $checkedPetTypeId) {
          foreach ($petTypes as $petType) {
            $this->checkPetType($petType, $checkedPetTypeId, array($petType));
          }
        }

        return View::make('articles.edit')
          ->with('article', $article)
          ->with('petTypes', $petTypes);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(StoreArticle $request, $id)
    {
      $validated = $request->validated();

      $article = Article::find($id);
      if ($article->user_id != Auth::id()) {
        abort(403, 'Cannot edit articles you don\'t own!');
      }

      $article->title = $request->input('title');
      //Clean input to prevent XSS attacks!
      $article->content = clean($request->input('content'));
      $pettypeids = $request->input('pettype'); //[1, 2, 4]
      if ($pettypeids == NULL)
        $pettypeids = [];
      $article->petTypes()->sync($pettypeids);
      $article->save();

      //ProcessNewArticleEmails::dispatch($article)->onQueue('lowPriorityEmails');

      //Redirect
      Session::flash('message', 'Successfully updated article!');
      return Redirect::to('articles');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      $article = Article::find($id);
      if ($article->user_id != Auth::id()) {
        abort(403, 'User attempting to delete an article that they do not own.');
      }
      $article->delete();

      Session::flash('message', 'Successfully deleted this article.');
      return Redirect::to('articles');
    }

    private function getPetTypeHierarchy()
    {
      $petTypes = PetType::all();
      $parentPets = array();
      //Process pet types into parent-child relationship
      foreach ($petTypes as $petType) {
        if ($petType->parent_id === NULL) {
          $parentPets[] = $petType;
        }
        else {
          foreach ($petTypes as $potentialParentPetType) {
            if ($petType->parent_id === $potentialParentPetType->id) {
              $potentialParentPetType->children[] = $petType;
              break;
            }
          }
        }
      }
      return $parentPets;
    }

    private function checkPetType($petType, $checkedPetTypeId, $parents)
    {
      if ($petType->id === $checkedPetTypeId) {
        $petType->checked = true;
        foreach ($parents as $parent) {
          $parent->open = true;
        }
      } else {
        $parents[] = $petType;
        foreach ($petType->children as $childPetType) {
          $parentsCopy = $parents;
          $this->checkPetType($childPetType, $checkedPetTypeId, $parentsCopy);
        }
      }
    }

    private function getUniqueParents($petType, & $foundParents, $ignore)
    {
      if ($petType->parent == NULL ||
        in_array($petType->parent_id, $foundParents))
      {
        return;
      }
      if (!in_array($petType->parent_id, $ignore))
      {
        $foundParents[] = $petType->parent_id;
      }
      $this->getUniqueParents($petType->parent, $foundParents, $ignore);
    }

    private function getUniqueChildren($petType, & $foundChildren, $ignore)
    {
      if (in_array($petType->id, $foundChildren))
      {
        return;
      }
      if (!in_array($petType->id, $ignore))
      {
        $foundChildren[] = $petType->id;
      }
      foreach($petType->childPetTypes as $childPetType)
      {
        $this->getUniqueChildren($childPetType, $foundChildren, $ignore);
      }
    }

    private function getNewsfeedArticles(Request $request)
    {
      //If not signed in, return top 20 articles by created date desc
      if (!Auth::check()) {
        return Article::latest()->with('user')->withCount('comments')->take(10)->get();
      }

      //Signed in. Get user's pet types.
      $userPetTypes = $request->user()->pets()->with('petType')->get()
                    ->map(function($item, $key){return $item->petType;});
      $userPetTypeIds = $userPetTypes->pluck('id')->toArray();
      $parentPetTypeIds = array();
      foreach($userPetTypes as $petType) {
        $this->getUniqueParents($petType, $parentPetTypeIds, $userPetTypeIds);
      }
      $childPetTypeIds = array();
      foreach($userPetTypes as $petType) {
        $this->getUniqueChildren($petType, $childPetTypeIds, $userPetTypeIds);
      }

      $top10WithUserPetTypes = Article::with('user')->withCount('comments')
      ->whereHas('petTypes', function($query) use($userPetTypeIds) {
        $query->whereIn('pet_type_id', $userPetTypeIds);
      })->latest()->take(10)->get();
      $top10WithUserPetTypeIds = $top10WithUserPetTypes->pluck('id')->toArray();

      $top10WithParentPetTypes = Article::with('user')->withCount('comments')
      ->whereHas('petTypes', function($query) use($parentPetTypeIds) {
        $query->whereIn('pet_type_id', $parentPetTypeIds);

resources/views/articles/create.blade.php
@extends('layouts.app')

@section('header')
Create a new Article
@endsection

@section('content')
<form method="POST" action="{{url('articles')}}">
  {{csrf_field()}}
  <label for="title">Title:</label>
  <input type="text" name="title" id="title" class="form-control"
    value="{{old('title')}}"></input>
  <br/>
  <span>Relevant Pet Types:</span>
  <pet-type-selector :initial-pet-types="{{json_encode($petTypes)}}"></pet-type-selector>
  <textarea id="article-editor" name="content" placeholder="Type your article here..."></textarea>
  <input class="btn btn-primary" type="submit" value="Create article"></input>
</form>
<textarea id="old-article-content" style="display: none;">{{old('content')}}</textarea>
@endsection

resources/views/articles/edit.blade.php
@extends('layouts.app')

@section('header')
Edit Article
@endsection

@section('content')
<form method="POST" action="{{url('articles/' . $article->id)}}">
  {{csrf_field()}}
  <input name="_method" type="hidden" value="PUT"></input>
  <label for="title">Title:</label>
  <input type="text" name="title" id="title" class="form-control"
    value="{{old('title', $article->title)}}"></input>
  <br/>
  <span>Relevant Pet Types:</span>
  <pet-type-selector :initial-pet-types="{{json_encode($petTypes)}}"></pet-type-selector>
  <textarea id="article-editor" name="content" placeholder="Type your article here..."></textarea>
  <input class="btn btn-primary" type="submit" value="Update article"></input>
</form>
<textarea id="old-article-content" style="display: none;">{{old('content', $article->content)}}</textarea>
@endsection

resources/views/articles/index.blade.php
@extends('layouts.app')

@section('header')
My Articles
@endsection

@section('content')
@if (count($articles) > 0)
<a href="{{URL::to('articles/create/')}}">Create an article</a>
<table class="htable table-striped table-bordered">
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Creation date/time (UTC time)</th>
    </tr>
  </thead>
  <tbody>
    @foreach($articles as $key => $value)
      <tr>
        <td>{{ $value->title }}</td>
        <td>{{ $value->content_preview }}</td>
        <td>{{ $value->created_at}}</td>
        <td>
          <!--Edit-->
          <a class="btn btn-small btn-info" href="{{URL::to('articles/' . $value->id . '/edit')}}">Edit</a>
        </td>
        <td>
          <form method="POST" action="{{url('articles/' . $value->id)}}" class="pull-right">
            {{csrf_field()}}
            <input name="_method" type="hidden" value="DELETE"></input>
            <input class="btn btn-danger" type="submit" value="Delete"></input>
          </form>
        </td>
      </tr>
    @endforeach
  </tbody>
</table>
@else
<p>You have no articles!<p>
@endif
<a href="{{URL::to('articles/create/')}}">Create an article</a>
@endsection

resources/views/articles/newsfeed.blade.php
@extends('layouts.app')

@section('content')
@guest
<p>You aren't signed in! <a href="{{ route('login') }}">{{ __('Login') }}</a> now to see articles relevant to your pets.</p>
@elseif (Auth::user()->pets()->count() === 0)
<p>You have no pets! <a href="{{URL::to('pets/create')}}">Add a pet now</a> now to see articles relevant to your pets.</p>
@endauth

@foreach($articles as $article)
<h2 class="nomargin"><a href="{{ URL::to('articles/' . $article->id)}}">{{$article->title}}</a></h2>
<small>By {{$article->user->name}} - {{$article->comments_count}} comment{{$article->comments_count == 1 ? '' : 's'}}</small>
<br/><small>{{$article->days_old_description}}</small>
<div class="gap"></div>
{!!$article->content_preview_with_tags!!}
<a href="{{ URL::to('articles/' . $article->id)}}">Read full article</a>
<hr/>
<br/>
@endforeach

@endsection

resources/views/articles/show.blade.php
@extends('layouts.app')

@section('content')
@guest
<small>You aren't signed in! <a href="{{ route('login') }}">{{ __('Login') }}</a> now to see articles relevant to your pets.</small>
@elseif (Auth::user()->pets()->count() === 0)
<small>You have no pets! <a href="{{URL::to('pets/create')}}">Add a pet now</a> now to see articles relevant to your pets.</small>
@endguest

<h1 class="nomargin">{{$article->title}}</h1>
<small>By {{$article->user->name}}</small>
<br/><small>{{$article->days_old_description}}</small>
<div class="gap"></div>
{!!$article->content!!}
<hr/>
<h3>Comments</h3>
@if($article->comments()->count() === 0)
<p>This article has no comments at the moment.</p>
@endif
@foreach($article->comments as $comment)
<p>{{$comment->content}}</p>
<small>By {{$comment->user->name}}</small>
<hr/>
@endforeach
@guest
<a href="{{ route('login') }}">{{ __('Login') }}</a> to add a comment.
@else
<form method="POST" action="{{url('articles/storeComment')}}">
  {{csrf_field()}}
  <textarea name="content" id="content" class="form-control" placeholder="Your comment here...">
    {{old('content')}}</textarea>
  <br/>
  <input type="hidden" name="article_id" id= "article_id" value="{{$article->id}}"></input>
  <input class="btn btn-primary" type="submit" value="Add Comment"></input>
</form>
@endguest
@endsection